/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "reqtransfer.h"

bool_t
xdr_filebytes (XDR *xdrs, filebytes objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, MAXLEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_filebytes (xdrs, objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_send_ (XDR *xdrs, send_ *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->value, REQUEST_VALUE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, REQUEST_VALUE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_file (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->request_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->total))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_put_req (XDR *xdrs, put_req *objp)
{
	register int32_t *buf;

	 if (!xdr_send_ (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_ (XDR *xdrs, request_ *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->value, REQUEST_VALUE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, REQUEST_VALUE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->request_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->recieved))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_request (XDR *xdrs, get_request *objp)
{
	register int32_t *buf;

	 if (!xdr_request_ (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->value, REQUEST_VALUE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, REQUEST_VALUE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_file (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->response_type))
		 return FALSE;
	return TRUE;
}
